import { query } from '../config/db.js';
import { generateTemplate } from '../services/collineBot.js';

async function getOwnedShopId(userId) {
  const result = await query('SELECT id, name FROM shops WHERE owner_id = $1', [userId]);
  return result.rows[0] || null;
}

// Ask Colline to generate a new reusable template for a category.
export async function generateNewTemplate(req, res) {
  const { category, productHint } = req.body;
  try {
    const shop = await getOwnedShopId(req.user.id);
    if (!shop) return res.status(403).json({ error: 'Open your shop before creating templates.' });

    const generated = await generateTemplate({ shopName: shop.name, category, productHint });

    const result = await query(
      `INSERT INTO product_templates (shop_id, name, category, title_template, description_template, specs_template, suggested_image_urls, generated_by_ai)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,
      [
        shop.id, generated.name, generated.category, generated.titleTemplate, generated.descriptionTemplate,
        generated.specsTemplate, generated.suggestedImageUrls, generated.generatedByAi
      ]
    );

    return res.status(201).json({ message: 'Template generated by Colline.', template: result.rows[0] });
  } catch (err) {
    console.error('Generate template error:', err);
    return res.status(500).json({ error: 'Could not generate template.' });
  }
}

export async function myTemplates(req, res) {
  try {
    const shop = await getOwnedShopId(req.user.id);
    if (!shop) return res.json({ templates: [] });
    const result = await query('SELECT * FROM product_templates WHERE shop_id = $1 ORDER BY created_at DESC', [shop.id]);
    return res.json({ templates: result.rows });
  } catch (err) {
    console.error('My templates error:', err);
    return res.status(500).json({ error: 'Could not load templates.' });
  }
}

export async function deleteTemplate(req, res) {
  try {
    const shop = await getOwnedShopId(req.user.id);
    if (!shop) return res.status(403).json({ error: 'You do not have a shop.' });
    await query('DELETE FROM product_templates WHERE id = $1 AND shop_id = $2', [req.params.id, shop.id]);
    return res.json({ message: 'Template removed.' });
  } catch (err) {
    console.error('Delete template error:', err);
    return res.status(500).json({ error: 'Could not remove template.' });
  }
}
