-- JEDIDA Marketplace — Phase 2 schema
-- Seller flow: shop categories, products (eBay-style listing), reusable
-- listing templates, AI-bot processing fields, and admin→seller notifications.

CREATE TYPE product_category AS ENUM (
    'agriculture', 'electronics', 'fashion', 'home_and_garden', 'health_and_beauty',
    'vehicles', 'food_and_beverages', 'sports_and_outdoors', 'books_and_media',
    'toys_and_kids', 'art_and_crafts', 'services', 'other'
);

CREATE TYPE product_condition AS ENUM ('new', 'used_like_new', 'used_good', 'used_fair');
CREATE TYPE listing_status AS ENUM ('draft', 'pending_review', 'active', 'paused', 'sold_out', 'rejected');

-- ===== Add agriculture-aware category + default currency to shops =====
ALTER TABLE shops ADD COLUMN IF NOT EXISTS primary_category product_category DEFAULT 'other';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'USD';

-- ===== PRODUCT LISTING TEMPLATES (reusable, generated by "Colline") =====
CREATE TABLE product_templates (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id             UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    name                VARCHAR(255) NOT NULL,
    category            product_category NOT NULL DEFAULT 'other',
    title_template      VARCHAR(255),
    description_template TEXT,
    specs_template      JSONB DEFAULT '{}',       -- e.g. {"material": "", "weight": "", "origin": ""}
    suggested_image_urls TEXT[] DEFAULT '{}',      -- sourced/generated by Colline
    generated_by_ai     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_templates_shop ON product_templates(shop_id);

-- ===== PRODUCTS =====
CREATE TABLE products (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id             UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    template_id         UUID REFERENCES product_templates(id),
    title               VARCHAR(255) NOT NULL,
    description         TEXT,
    category            product_category NOT NULL DEFAULT 'other',
    condition           product_condition NOT NULL DEFAULT 'new',
    price               NUMERIC(12,2) NOT NULL,
    currency            VARCHAR(10) NOT NULL DEFAULT 'USD',
    quantity_available  INTEGER NOT NULL DEFAULT 1,
    sku                 VARCHAR(100),
    images              TEXT[] DEFAULT '{}',
    specs               JSONB DEFAULT '{}',
    location_city       VARCHAR(100),
    location_country    VARCHAR(100),
    shipping_options     JSONB DEFAULT '[]',       -- e.g. [{"label":"Local pickup","fee":0}]
    status              listing_status NOT NULL DEFAULT 'pending_review',
    -- AI processing (Nsubuga Joseph polishes listings before they go live)
    ai_polished         BOOLEAN NOT NULL DEFAULT FALSE,
    ai_polish_notes     TEXT,
    views_count         INTEGER NOT NULL DEFAULT 0,
    orders_count        INTEGER NOT NULL DEFAULT 0,
    is_trending         BOOLEAN NOT NULL DEFAULT FALSE,
    is_featured         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_shop ON products(shop_id);
CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_status ON products(status);

CREATE TRIGGER trg_templates_updated_at BEFORE UPDATE ON product_templates
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ===== NOTIFICATIONS (admin -> seller, system events) =====
CREATE TYPE notification_type AS ENUM (
    'shop_approved', 'shop_rejected', 'product_approved', 'product_rejected',
    'new_order', 'kyc_update', 'payout_released', 'system_announcement', 'ad_message'
);

CREATE TABLE notifications (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type                notification_type NOT NULL,
    title               VARCHAR(255) NOT NULL,
    body                TEXT,
    is_read             BOOLEAN NOT NULL DEFAULT FALSE,
    metadata            JSONB DEFAULT '{}',
    sent_by             UUID REFERENCES users(id), -- NULL = system-generated
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_user ON notifications(user_id, is_read);
