import { query } from '../../src/config/db.js';
import { log, recordAction } from './tausiService.js';

export async function createCampaign({ shopId, productId, title, imageUrl, budget, startsAt, endsAt }) {
  const result = await query(
    `INSERT INTO ad_campaigns (shop_id, product_id, title, image_url, budget, starts_at, ends_at, status)
     VALUES ($1,$2,$3,$4,$5,$6,$7,'pending_review') RETURNING *`,
    [shopId, productId || null, title, imageUrl || null, budget || 0, startsAt || null, endsAt || null]
  );
  await log('tausi', 'info', 'ads', `Campaign "${title}" submitted for review.`);
  return result.rows[0];
}

export async function reviewCampaign(id, decision) {
  const status = decision === 'approve' ? 'active' : 'rejected';
  const result = await query('UPDATE ad_campaigns SET status = $1 WHERE id = $2 RETURNING *', [status, id]);
  await recordAction({ actor: 'tausi', actionType: 'review_campaign', payload: { id, status }, status: 'executed' });
  return result.rows[0];
}

export async function listCampaigns({ status } = {}) {
  const where = status ? 'WHERE status = $1' : '';
  const values = status ? [status] : [];
  const result = await query(`SELECT * FROM ad_campaigns ${where} ORDER BY created_at DESC`, values);
  return result.rows;
}

export async function recordSpend(id, amount) {
  const result = await query('UPDATE ad_campaigns SET spent = spent + $1 WHERE id = $2 RETURNING *', [amount, id]);
  return result.rows[0];
}

// Performance score: simple spend-efficiency proxy — orders generated by
// the campaign's product per dollar spent, scaled 0-100.
export async function computePerformanceScores() {
  const campaigns = await query(`SELECT * FROM ad_campaigns WHERE status = 'active'`);
  let updated = 0;
  for (const c of campaigns.rows) {
    if (!c.product_id) continue;
    const product = await query('SELECT orders_count FROM products WHERE id = $1', [c.product_id]);
    const orders = Number(product.rows[0]?.orders_count || 0);
    const spend = Number(c.spent) || 1;
    const score = Math.min(100, Math.round((orders / spend) * 1000));
    await query('UPDATE ad_campaigns SET performance_score = $1 WHERE id = $2', [score, c.id]);
    updated += 1;
  }
  await log('tausi', 'info', 'ads', `Recomputed performance scores for ${updated} campaigns.`);
  return updated;
}

export async function activeAdsForMarketplace(limit = 5) {
  const result = await query(
    `SELECT * FROM ad_campaigns WHERE status = 'active' ORDER BY performance_score DESC LIMIT $1`,
    [limit]
  );
  return result.rows;
}
